### ISSUE TITLE
    Error: seedMultibase required

### ISSUE THREAD

**Issue by HelgeKrueger** [w3c/vc-di-eddsa-test-suite#28]
Hi.

If I follow the instructions to run the tests, they fail with:

```bash
  eddsa-rdfc-2022 (create)
    ❌ "before all" hook in "eddsa-rdfc-2022 (create)"
    Error: seedMultibase required
```

This seems to be set by the environment variable `KEY_SEED_DB`. I have no idea what this could be.

**Comment by aljones15** [comment]
`KEY_SEED_DB` is a base58 key seed used to sign the zcaps on our endpoint, my apologies about this we are looking into making the suites more resilient, unfortunately I don't think we can give you a `KEY_SEED` for the issuer and verifier endpoints, but we might be able to make the test ignore DB if there is no key seed set.

**Comment by HelgeKrueger** [comment]
Thanks for the information. With the key seed, I can also run some 78% of tests successfully.

Unfortunately, I think I'm still missing something. I was hoping for a way to just execute local tests, see https://github.com/w3c/vc-test-suite-implementations#testing-locally

So something like create `localImplementationsConfig.cjs` and then only calls to localhost are done. Is a functionality like that planned?

**Comment by JSAssassin** [comment]
@HelgeKrueger You should be able to run the tests only against local implementations. After adding the config file, you can update the tags in the test suite (https://github.com/w3c/vc-di-eddsa-test-suite/blob/main/tests/10-rdfc-create.js#L16, https://github.com/w3c/vc-di-eddsa-test-suite/blob/main/tests/20-rdfc-verify.js#L14 and https://github.com/w3c/vc-di-eddsa-test-suite/blob/main/tests/30-rdfc-interop.js#L10) that is used to filter implementations to use a specific tag that is in your config file. See - https://github.com/w3c/vc-test-suite-implementations/pull/10/files

**Comment by HelgeKrueger** [comment]
Thanks! I got it working now.
