### ISSUE TITLE
Is eddsa multikey implementation correct?

### ISSUE THREAD

**Issue by rflechtner** [w3c/vc-di-eddsa-test-suite#44]
I'm confused by the implementation of the eddsa Multikey that this test suite assumes. 
Both according to https://github.com/multiformats/multicodec/blob/master/table.csv and https://w3c-ccg.github.io/did-method-key/#signature-method-creation-algorithm the prefix for an ed25519 public key is `0xed`, but the implementation here (incorrectly, I'd say?) assumes a prefix of `0xed, 0x01` resulting in a hard-coded assertion that `did:key` DIDs must begin with `z6Mk`. Can you clarify where this extra byte is coming from?

**Comment by ntn-x2** [comment]
cc @msporny, addressing this would help us greatly clarifying our assumptions about the subject 😃

**Comment by aljones15** [comment]
@rflechtner @msporny In additionto Manu's comments, the eddsa spec explicitly states the raw binary value as `0xed01` here: https://w3c.github.io/vc-di-eddsa/#:~:text=in%20this%20specification.-,The%20publicKeyMultibase%20value%20of%20the%20verification%20method%20MUST%20start%20with%20the,using%20base%2D58%2Dbtc.%20Any%20other%20encoding%20MUST%20NOT%20be%20allowed.,-Developers%20are%20advised

**Comment by rflechtner** [comment]
@msporny @aljones15 thanks for clarifying! I have to admit I completely glossed over the entire varint encoding bit in the specifications. Maybe it's worth highlighting this a little more? We'll fix this and then have another go at integrating with the test suite.

**Comment by aljones15** [comment]
> @msporny @aljones15 thanks for clarifying! I have to admit I completely glossed over the entire varint encoding bit in the specifications. Maybe it's worth highlighting this a little more? We'll fix this and then have another go at integrating with the test suite.

I am not very active with the spec community, but the signature suite specs do directly tell you the byte prefixes so I would stick would them if you see them.

**Comment by rflechtner** [comment]
@msporny @aljones15 Closing as when respecting varint encoding of the prefix we managed to intergrate with the test suite and have all tests passing  🚀
